/*
 * This file is generated by jOOQ.
*/
package com.cathyxz.stockviewer.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.stockviewer_user_id_seq</code>
     */
    public static final Sequence<Long> STOCKVIEWER_USER_ID_SEQ = new SequenceImpl<Long>("stockviewer_user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
