/*
 * This file is generated by jOOQ.
*/
package com.cathyxz.stockviewer.jooq;


import com.cathyxz.stockviewer.jooq.tables.StockviewerUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.stockviewer_user</code>.
     */
    public static final StockviewerUser STOCKVIEWER_USER = com.cathyxz.stockviewer.jooq.tables.StockviewerUser.STOCKVIEWER_USER;
}
