/*
 * This file is generated by jOOQ.
*/
package com.cathyxz.stockviewer.jooq.tables;


import com.cathyxz.stockviewer.jooq.Keys;
import com.cathyxz.stockviewer.jooq.Public;
import com.cathyxz.stockviewer.jooq.tables.records.StockviewerUserRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockviewerUser extends TableImpl<StockviewerUserRecord> {

    private static final long serialVersionUID = -37714442;

    /**
     * The reference instance of <code>public.stockviewer_user</code>
     */
    public static final StockviewerUser STOCKVIEWER_USER = new StockviewerUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StockviewerUserRecord> getRecordType() {
        return StockviewerUserRecord.class;
    }

    /**
     * The column <code>public.stockviewer_user.id</code>.
     */
    public final TableField<StockviewerUserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('stockviewer_user_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.stockviewer_user.username</code>.
     */
    public final TableField<StockviewerUserRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>public.stockviewer_user.email</code>.
     */
    public final TableField<StockviewerUserRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * The column <code>public.stockviewer_user.password</code>.
     */
    public final TableField<StockviewerUserRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

    /**
     * Create a <code>public.stockviewer_user</code> table reference
     */
    public StockviewerUser() {
        this("stockviewer_user", null);
    }

    /**
     * Create an aliased <code>public.stockviewer_user</code> table reference
     */
    public StockviewerUser(String alias) {
        this(alias, STOCKVIEWER_USER);
    }

    private StockviewerUser(String alias, Table<StockviewerUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private StockviewerUser(String alias, Table<StockviewerUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StockviewerUserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STOCKVIEWER_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockviewerUser as(String alias) {
        return new StockviewerUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StockviewerUser rename(String name) {
        return new StockviewerUser(name, null);
    }
}
